### ISSUE TITLE
Adding new contributor 

### ISSUE THREAD

**Issue by maks-us** [wikihouseproject/map.wikihouse.cc#12]
I tried to add myself as a new contributor and it failed
https://map.wikihouse.cc/contributors/new

![screen shot 2017-03-17 at 10 45 18 pm](https://cloud.githubusercontent.com/assets/8204705/24068370/869b1210-0b63-11e7-84f9-b7b528739a66.png)
![screen shot 2017-03-17 at 10 44 45 pm](https://cloud.githubusercontent.com/assets/8204705/24068369/869b12d8-0b63-11e7-9d74-a29ca1f074fe.png)

**Comment by jonleighton** [comment]
Hi @maks-us, I've [fixed a related problem](https://github.com/wikihouseproject/map.wikihouse.cc/commit/2269670bd646a50795aa3419806fae902836c6d6), although the symptom was slightly different. Do you still have trouble making your submission?

(BTW, please bear in mind the map is still a work in progress.)
